version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: real_estate_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://real_estate_user:password@db:5432/real_estate_db
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
